apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: mysql
spec:
  containers:
  - name: mysql-container
    image: alpine
    command: ['sleep',"infinity"]
    imagePullPolicy: IfNotPresent
    env:
     - name: mysql_password
       valueFrom:
        secretKeyRef:
          name: mysql-password
          key: MYSQL_ROOT_PASSWORD
