namespace: 
 name: dev

replicas:
  count: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 20
  targetMemoryUtilizationPercentage: 20
  pps: "2k" # packets-per-seconds
