apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-datasource
  namespace: {{ .Release.Namespace}}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server:80
        access: proxy
        isDefault: true
      - name: Alertmanager
        type: prometheus
        url: http://prometheus-alertmanager:9093
        access: proxy
        isDefault: false
