apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
type: Opaque
data:
  admin-password: Z3JhZmFuYQ== # grafana #echo -n 'your-password' | base64
  admin-username: "YWRtaW4=" # admin
