app:
  name: nginx

service:
  type: ClusterIP
  port: 80
  targetPort: 80

container:
  image: nginx:latest
  name: nginx

replicas:
  count: 1

resources:
  requests:
    memory: "8Mi"
    cpu: "25m"
  limits:
    memory: "16Mi"
    cpu: "50m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
  pps: "1k" # packets-per-seconds
