apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}-deployment-{{ .Release.Namespace }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
